server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format-sql: true
      dialect: .org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
    defer-datasource-initialization: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/community?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATA_SOURCE_USER}
    password: ${SPRING_DATA_SOURCE_PASSWORD}

springdoc:
  model-and-view-allowed: true

jwt:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 4
  refresh-token:
    plus-hour: 12
  expiration: 3600000